from ..common.constants import (
    INTENT_RESERVE_CLASS,
    INTENT_FAQ,
    INTENT_HANDOVER,
    INTENT_VERIFICATION,
    INTENT_CLARIFY,
    INTENT_TICKET,
    INTENT_TICKET_STATUS,
    INTENT_AVAILABLE_CLASSES,
    INTENT_CONTRACT_STATUS,
    INTENT_CRM_MEMBER_BALANCE,
    INTENT_ACK,
    INTENT_MARKETING_OPTOUT,
    INTENT_MARKETING_OPTIN,
)

INTENTS = {
    INTENT_RESERVE_CLASS: {"requires_confirmation": True},
    INTENT_FAQ: {"requires_confirmation": False},
    INTENT_HANDOVER: {"requires_confirmation": False},
    INTENT_VERIFICATION: {"requires_confirmation": False},
    INTENT_CLARIFY: {"requires_confirmation": False},
    INTENT_TICKET: {"requires_confirmation": True},
    INTENT_AVAILABLE_CLASSES: {"requires_confirmation": False},
    INTENT_CONTRACT_STATUS: {"requires_confirmation": True},
    INTENT_CRM_MEMBER_BALANCE: {"requires_confirmation": True},
    INTENT_ACK: {"requires_confirmation": False},
    INTENT_MARKETING_OPTOUT: {"requires_confirmation": True},
    INTENT_MARKETING_OPTIN: {"requires_confirmation": True},
}
