import os

STATE_AWAITING_CONFIRMATION = "awaiting_confirmation"
STATE_AWAITING_VERIFICATION = "awaiting_verification"
STATE_AWAITING_CLASS_SELECTION = "awaiting_class_selection"
STATE_AWAITING_MESSAGE = "awaiting_message"
STATE_AWAITING_CHALLENGE = "awaiting_challenge"
STATE_AWAITING_HANDOVER_COMMENT = "awaiting_handover_comment"
STATE_AWAITING_TICKET_COMMENT = "awaiting_ticket_comment"

SESSION_TIMEOUT_SECONDS = 120
DEFAULT_NLU_CONFIDENCE = 1.0
DEFAULT_CHANNEL = "whatsapp"
WEB_CHANNEL = "web"
OTP_LENGTH=6
OTP_MAX_ATTEMPTS = 3
CRM_VERIFICATION_TTL_SECONDS = 15 * 60 
CRM_VERIFICATION_CODE_SECONDS = 5 * 60 
CRM_VERIFICATION_CODE_MINUTES = 5
CRM_COOLDOWN_SECONDS = 30 * 60 
CRM_OTP_RESEND_MIN_SECONDS = 60
CRM_MARKETING_AGREEMENT_ID = 1
AVAILABLE_CLASSES_TOP = 10 
HISTORY_FETCH_LIMIT = 10
DATE_SLICE_START = 0
DATE_SLICE_END = 10
TIME_SLICE_START = 11
TIME_SLICE_END = 16
CLASS_INDEX_REGEX=r"\b(\d{1,2})\b"
ISO_DATE_REGEX=r"\b(\d{4}-\d{2}-\d{2})\b"
FAQ_AI_HISTORY_LIMIT=6
STR_CHUNK_SCORE="score"
ENUM_CRM_RETURN_OK=0
ENUM_CRM_RETURN_ALREADY_BOOKED=1
ENUM_CRM_RETURN_FAIL=2

#intents
INTENT_RESERVE_CLASS="reserve_class"
INTENT_FAQ="faq"
INTENT_HANDOVER="handover"
INTENT_VERIFICATION="verification"
INTENT_CLARIFY="clarify"
INTENT_TICKET="ticket"
INTENT_TICKET_STATUS="ticket_status"
INTENT_AVAILABLE_CLASSES="crm_available_classes"
INTENT_CONTRACT_STATUS="crm_contract_status"
INTENT_CRM_MEMBER_BALANCE="crm_member_balance"
INTENT_ACK="ack"
INTENT_MARKETING_OPTOUT="marketing_optout"
INTENT_MARKETING_OPTIN="marketing_optin"


_VALID_INTENTS = {
    INTENT_RESERVE_CLASS,
    INTENT_FAQ,
    INTENT_HANDOVER,
    INTENT_VERIFICATION,
    INTENT_CLARIFY,
    INTENT_TICKET,
    INTENT_TICKET_STATUS,
    INTENT_AVAILABLE_CLASSES,
    INTENT_CONTRACT_STATUS,
    INTENT_CRM_MEMBER_BALANCE,
    INTENT_ACK,
    INTENT_MARKETING_OPTOUT,
    INTENT_MARKETING_OPTIN,
}